### ISSUE TITLE
Empty package when downloaded from npm.

### ISSUE THREAD

**Issue by Donald47** [ryanep/jest-serializer-gql#10]
After upgrading the the latest version (1.1.0) the folder in node modules only contains the following files:
```
CODE_OF_CONDUCT.md
LICENSE
README.md
package.json
```
Also it has an unpacked size of 8.73 kB contrasted with the 94kb zip file on github. Looks a lot like this issue: https://github.com/semantic-release/semantic-release/issues/615

**Comment by ryanep** [comment]
🤦 Thanks for flagging this. I've republished the package correctly as v1.1.1.
